services:
  mysql8033:
    container_name: mysql8033_rodteus
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    restart: always
    environment:
      MYSQL_DATABASE: rodteus_development
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/dbs:/var/lib/mysql

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/code
      - ./typings:/typings
      - ./environment:/environment
    ports:
      - 3450:3450
    command: sh -c "npm install && npm run dev"

  backend_1:
    container_name: backend_1
    build:
      context: .
      dockerfile: ./backend/nodejs-express-api/Dockerfile
    volumes:
      - ./backend/nodejs-express-api:/code
      - ./typings:/typings
    ports:
      - 3490:3490
    command: sh -c "npm install && npm run dev"